-- =====================================================================
-- Phase 11+ — Expand `categories` to the 50 most popular slugs the
-- client picker now offers. Idempotent: ON CONFLICT (slug) DO NOTHING.
-- =====================================================================

insert into public.categories (slug, name, color, icon) values
  ('ai',                 'AI',                 '#FFE600', '🤖'),
  ('stocks',             'Stocks',             '#36D399', '📊'),
  ('finance',            'Finance',            '#36D399', '💵'),
  ('elections',          'Elections',          '#FF6B3D', '🗳️'),
  ('geopolitics',        'Geopolitics',        '#FF4757', '🌍'),
  ('climate',            'Climate',            '#36D399', '🌡️'),
  ('science',            'Science',            '#4DA3FF', '🔬'),
  ('health',             'Health',             '#FF4757', '🩺'),
  ('covid',              'COVID',              '#FF4757', '🦠'),
  ('gaming',             'Gaming',             '#A371F7', '🎮'),
  ('esports',            'Esports',            '#A371F7', '🕹️'),
  ('movies',             'Movies',             '#FF6FB5', '🎥'),
  ('tv',                 'TV',                 '#FF6FB5', '📺'),
  ('music',              'Music',              '#FF6FB5', '🎵'),
  ('celebrities',        'Celebrities',        '#FF6FB5', '⭐'),
  ('fashion',            'Fashion',            '#FF6FB5', '👗'),
  ('art',                'Art',                '#A371F7', '🎨'),
  ('books',              'Books',              '#4DA3FF', '📚'),
  ('education',          'Education',          '#4DA3FF', '🎓'),
  ('startups',           'Startups',           '#FFE600', '🚀'),
  ('vc',                 'VC',                 '#FFE600', '💼'),
  ('real-estate',        'Real Estate',        '#36D399', '🏠'),
  ('energy',             'Energy',             '#FFB800', '⚡'),
  ('oil',                'Oil',                '#FFB800', '🛢️'),
  ('commodities',        'Commodities',        '#FFB800', '🌾'),
  ('metals',             'Metals',             '#FFB800', '🥇'),
  ('macro',              'Macro',              '#36D399', '🏛️'),
  ('rates',              'Rates',              '#36D399', '📉'),
  ('inflation',          'Inflation',          '#FF4757', '📊'),
  ('jobs',               'Jobs',               '#36D399', '💼'),
  ('trade',              'Trade',              '#36D399', '🚢'),
  ('war',                'War',                '#FF4757', '⚔️'),
  ('space',              'Space',              '#4DA3FF', '🚀'),
  ('weather',            'Weather',            '#4DA3FF', '🌦️'),
  ('natural-disasters',  'Disasters',          '#FF4757', '🌪️'),
  ('olympics',           'Olympics',           '#FFE600', '🏅'),
  ('soccer',             'Soccer',             '#36D399', '⚽'),
  ('nba',                'NBA',                '#FF8A3D', '🏀'),
  ('nfl',                'NFL',                '#A371F7', '🏈'),
  ('mlb',                'MLB',                '#4DA3FF', '⚾'),
  ('tennis',             'Tennis',             '#36D399', '🎾'),
  ('f1',                 'F1',                 '#FF4757', '🏎️'),
  ('ufc',                'UFC',                '#FF4757', '🥋'),
  ('boxing',             'Boxing',             '#FF4757', '🥊')
on conflict (slug) do nothing;
